name: rafiq_barmaja
description: "تطبيق رفيق البرمجة - تعليم البرمجة بالعربية"
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    provider: any
    shared_preferences: any
    flutter_localizations: any
    intl: any
    cupertino_icons: any

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: any

flutter:
    uses-material-design: true
    fonts:
      - family: Cairo
        fonts:
          - asset: assets/fonts/Cairo-Regular.ttf
          - asset: assets/fonts/Cairo-Bold.ttf
