name: Build Rafiq Barmaja APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Go to project root and Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          ls -la pubspec.yaml
          flutter pub get

      - name: Go to project root and Build APK
        run: |
          cd $GITHUB_WORKSPACE
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rafiq_barmaja_apk
          path: build/app/outputs/flutter-apk/app-release.apk
